// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DfvApiPrueba.Models
{
    public partial class Article
    {
        public string ArticleCode { get; set; }
        public string ArticleDescription { get; set; }
        public string UnitOfMeasure { get; set; }
        public System.Decimal QuantityAvailable { get; set; }
        public System.Decimal QuantityToStock { get; set; }
    }
}