// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DfvApiPrueba.Models
{
    public partial class Product
    {
        public int venfac { get; set; }
        public string codcli { get; set; }
    }
}